server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge_fase3?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: RubieBerilo@991003
    hikari:
      read-only: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: America/Sao_Paulo

  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/